### PR TITLE
Reorganize developer guide.

### PR DESCRIPTION
**Pull request by tribeiro**
The main change is that all the "guides" are now under the "guidelines" session. This reorganization left a few pages (including the front page) empty. We should fill these up with content later but I am trying to avoid makind changes and reorganize the page at the same time to make it easier to review.

### CODE REVIEW

**Review by wvreeven — APPROVED** [review]
Looks good to me.

**Comment by couger01** [comment]
Some of the includes in the python guide are still broken(For example I include Jenkinsfile information in a separate file). Not sure if we need deployment guidelines considering it's empty and we have documentation on ts-cycle-build. We could comment out the toc tree until content is actually written for it. Docker guidelines might be deprecated considering the standardization of the develop-env. Maybe comment out that toctree as well until we update to new content.

**Comment by wvreeven** [comment]
> Docker guidelines might be deprecated considering the standardization of the develop-env.

We use Docker files for many other purposes so I think we should keep that.

**Review by couger01 — APPROVED** [review]
LGTM.

**Pull request merged**
